global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'todo'
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:1323']
        labels:
          group: 'production'
